[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.devnet]
solrush_liquidity_pool = "SRLPooL111111111111111111111111111111111111"
solrush_swap = "SRSwap1111111111111111111111111111111111111"
solrush_token = "SRToken111111111111111111111111111111111111"
solrush_rewards = "SRReward111111111111111111111111111111111111"
solrush_perpetual = "SRPerp1111111111111111111111111111111111111"
solrush_admin = "SRAdmin111111111111111111111111111111111111"

[programs.localnet]
solrush_liquidity_pool = "SRLPooL111111111111111111111111111111111111"
solrush_swap = "SRSwap1111111111111111111111111111111111111"
solrush_token = "SRToken111111111111111111111111111111111111"
solrush_rewards = "SRReward111111111111111111111111111111111111"
solrush_perpetual = "SRPerp1111111111111111111111111111111111111"
solrush_admin = "SRAdmin111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
